name: self_journie_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  double_back_to_close_app: ^2.1.0
  firebase_crashlytics: ^3.4.8
  intl: ^0.18.1
  flutter_screenutil: ^5.6.0
  google_fonts: ^4.0.4
  uuid:
  flutter: 
    sdk: flutter
  easy_search_bar: ^2.5.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

