// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEhc-tUJeIGK_3d5QqVabF51LGRqY9Vs8',
    appId: '1:536596601082:web:edbe5e9505b8e48c91d143',
    messagingSenderId: '536596601082',
    projectId: 'selfjournie-apps',
    authDomain: 'selfjournie-apps.firebaseapp.com',
    storageBucket: 'selfjournie-apps.appspot.com',
    measurementId: 'G-4SV4DR6X6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX1j7Hn8UppSGk41xRLuHBJ0bhMg1Xnp4',
    appId: '1:536596601082:android:fd35bf246a53ecc491d143',
    messagingSenderId: '536596601082',
    projectId: 'selfjournie-apps',
    storageBucket: 'selfjournie-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh9zri6udCTv4UGeKHjUaCwMK_1KTTifQ',
    appId: '1:536596601082:ios:d561d7554fb6e72e91d143',
    messagingSenderId: '536596601082',
    projectId: 'selfjournie-apps',
    storageBucket: 'selfjournie-apps.appspot.com',
    iosBundleId: 'com.arsdev.selfJournieApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh9zri6udCTv4UGeKHjUaCwMK_1KTTifQ',
    appId: '1:536596601082:ios:d561d7554fb6e72e91d143',
    messagingSenderId: '536596601082',
    projectId: 'selfjournie-apps',
    storageBucket: 'selfjournie-apps.appspot.com',
    iosBundleId: 'com.arsdev.selfJournieApps',
  );
}
